### ISSUE TITLE
Hero/Map Names - Translation Issues

### ISSUE THREAD

**Issue by Zemill** [koliva8245/Heroes.ReplayParser#16]
I am wondering if it would be worthwhile to pick up hero/map names without using their translations

I am told there is another attribute that can be used

The map is at EndOfGameTalentChoices[0]['m_stringData'][2]['m_value'] and the heroes are at EndOfGameTalentChoices[p]['m_stringData'][0]['m_value'] with 0 <= p < 10. 

I took a look for that object in the code and it is in one of the switch cases, but there is no definition for it

**Comment by koliva8245** [comment]
What do you mean there's no definition for it? That is where the values exists at.

**Comment by Zemill** [comment]
You are right, looks like my version is not updated for that.  Thought I did that when I added in the last commit..thanks!
