### ISSUE TITLE
Player PartyValue

### ISSUE THREAD

**Issue by Zemill** [koliva8245/Heroes.ReplayParser#18]
I wanted to find out if you are getting any good data out of the Player PartyValue object.

I get 0 for all players, regardless if they are in a party or not.  I checked my parser to yours and it appears our code is the same, so was curious.

**Comment by koliva8245** [comment]
It works. Did you set the `detailedBattleLobbyParsing` parameter to true for the `DataParser.ParseReplay(...)` method?

**Comment by Zemill** [comment]
I did not, that resolves the issue.  What else does that parameter control?  PartyValue appears to be the only value I haven't been receiving information for, other than maybe IsSilenced

**Comment by Zemill** [comment]
As far as I can tell, account level seems to be the only other one?

**Comment by koliva8245** [comment]
Yup

**Comment by Zemill** [comment]
Good deal, thanks for the info!
