### ISSUE TITLE
Regen Globe Pickup Attribute

### ISSUE THREAD

**Issue by Zemill** [koliva8245/Heroes.ReplayParser#19]
I am trying to find the data on regen globe pickups and have been unsuccessful.  Do you know where it is in the c# parser?

**Comment by koliva8245** [comment]
In the tracker events.  Look for `{StatGameEvent: {"RegenGlobePickedUp", , [{{"PlayerID"}, 10}], }}`

**Comment by Zemill** [comment]
Thanks,
Have you done any investigation into this event?  I was just looking at it, and it only gets hit twice for an entire replay by two different players.  That seems a bit low to me.  So I am curious if the data is subject, or if I am just not accessing it right.

**Comment by koliva8245** [comment]
Not really. I thought it would appear each time a globe was picked up for all players.  I'll look into it later.

**Comment by koliva8245** [comment]
It's definitely this event. I guess you're not accessing it right.

**Comment by Zemill** [comment]
Thanks for taking a look.  I went and tried another replay and the data looks better.  Must be either people suck at picking up regen globes in the one I was using or the data is sometimes suspect.....interesting.
